@extends('web')
@section('title','ORCA | Organisation for Research on China and Asia')
@section('meta_keywords', 'ORCA')
@section('meta_description', 'ORCA')

@section('content')

<style>
    .side-widget .float-icon {
    height :auto!important;
}
</style>

     <!-- Banner -->
<section class="shock-section has-overlay bg-image bg-fixed" data-bg-image="{{ URL::asset('images/Overview.jpeg') }}">
  <div class="banner vh-100 align-h-center align-v-center">
    <!-- Intro -->
    <div class="p-3 extended-intro">
      <div class="wrapper">
        <div class="left-column">
          <h2 class="title text-style-1 text-offset">
            <span class="text-1 rtalng filled white">THE 20th</span>
            
          </h2>
          <span class="text-2 text-style-2 fw-400 text-italic filled white">CENTRAL<br>COMMITTEE OVERVIEW</span>
          <div class="description text-style-12 gray">
         
            

          </div>                  
        </div>
      </div>
    </div>
  </div>          
  <!-- Overlay -->
  <div class="overlay" data-bg-color="#192a3d99"></div>
</section>

<style>
 

  .banner {
    position: relative;
    z-index: 1;
  }

  .title {
    position: relative;
    z-index: 2;
  }

  .text-1.outline.white {
    color: white;
       text-align:right!important;

  }

  .text-2 {
    color: white;
 
   
  }
  
  .rtalng {
         text-align:right!important;
  }
  
  
  .text-8 {
    color: white;
   
  }
  
  
</style>


      <!-- Banner -->
      <section class="shock-section bg-image bg-fixed" data-bg-image="{{ URL::asset('images/Overview.jpeg') }}">
        <div class="holder vh-75"></div>
      </section>
      
      
        <!-- Portfolio -->
    <section class="shock-section pt-5 pb-2 has-overlay">
      <div class="container" style="text-align:justify;">
          
            <p>  Date: 05/08/22<br></p>
        <h4 style="color: black; z-index:-1;" class="title black">
        
By <a style="color:red;" href="/author/rahul-karan-reddy">Rahul Karan Reddy</a> and <a style="color:red;" href="/author/omkar-bhole">Omkar Bhole</a></h4>
       
<br><br>

<section class="vc_row section-wrapper" style="text-align:justify;">
<div class="container">
<p style="text-align: justify; color:#000;">The Central Committee (CC) of the Communist Party of China (CPC) is one of the three most important political bodies in Chinese politics. It is elected every five years at the National Party Congress (NPC) from a pool of appointed delegates belonging to various sectors across China. At the recently concluded 20<sup>th</sup>&nbsp;National Party Congress, 376 members &ndash; 205 full and 171 alternate &ndash; were elected for the new Central Committee from 2296 delegates. This Central Committee will continue till 2027 and play a crucial role in CPC&rsquo;s decision-making. Amongst these Central Committee members, 24 members were appointed in the Politburo of CPC and seven out of these 24 were appointed to the Politburo Standing Committee &ndash; the most powerful political body in China. Seven members of the Central Military Commission are also from the new Central Committee.</p>
<h3 style="text-align: justify;color:#000;"><strong>Full and Alternate members</strong></h3>
<div class='tableauPlaceholder' id='viz1687129247810' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='Full&#47;Alt Dash ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_FullAlt&#47;FullAltDash&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='20thCCProject_FullAlt&#47;FullAltDash' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_FullAlt&#47;FullAltDash&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129247810');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;color:#000;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;">The current Central Committee is composed of 205 full members (2 more compared to 19<sup>th</sup>&nbsp;CC) and 171 alternate members (3 more compared to 19<sup>th</sup>&nbsp;CC). Full members have voting rights whereas alternate members do not. Alternate members fill vacancies that may get created among full members. The order among alternate members is decided as per the number of votes they received during the elections. Most of the full members hold important positions in various state and party organs both at the central and provincial levels, evident from the fact that Politburo and Politburo Standing Committee members are full CC members.</p>
<div class='tableauPlaceholder' id='viz1687129362328' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='New&#47;Retained ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_nuandalt&#47;NewRetained&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='20thCCProject_nuandalt&#47;NewRetained' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_nuandalt&#47;NewRetained&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129362328');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;color:#000;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;color:#000;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;">For the 20<sup>th</sup>&nbsp;CC, total 246 new members were appointed whereas 130 members were retained from the 19<sup>th</sup>&nbsp;CC. This takes the members replacement rate in CC to 65.42% (similar to as that of 19<sup>th</sup>&nbsp;CC), which s quite higher when compared to previous Central Committees (Refer to infographic for&nbsp;<a href="https://orcasia.org/graphs/">Minimum personnel replacement in 20<sup>th</sup>&nbsp;CC</a>). Amongst these new members, 92 members have earned full membership whereas 154 members belong to alternate membership. It indicates that replacement rate for full members is 44.88% whereas for alternate members, it is as high as 90.05%. Due to such high replacement ratio, it implies that alternate membership to CC may not constitute the core of decision-making apparatus in China.</p>
<p style="text-align: justify;color:#000;">Among the full members, apart from 92 new members, there are 42 members who have been promoted from 19<sup>th</sup>&nbsp;CC alternate membership. This will also be reflected in their promotions with respect to their positions and rank.</p>
<h3 style="text-align: justify;color:#000;"><strong>Gender and Ethnicity</strong></h3>
<div class='tableauPlaceholder' id='viz1687129377504' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='Gender ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_gender&#47;Gender&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='20thCCProject_gender&#47;Gender' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_gender&#47;Gender&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129377504');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;color:#000;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;color:#000;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;">The 20<sup>th</sup>&nbsp;CC comprises of 343 males (91.22%) and 33 females (8.78%). This is slightly higher compared to 19<sup>th</sup>&nbsp;CC where there were 30 women comprising 8.09% of total members. This gender imbalance is consistent with earlier pattern of overall under-representation of women in Chinese politics. This pattern is more severe in full membership where there are only 11 females out of 205 members (5.36%). This condition is slightly better in alternate membership as there are 22 women which makes up for 12.86% of total alternate members. However, none of these 33 females could earn a seat in the Politburo which has happened for the first time since 1997. The average age of female representatives has gone down from 61 in 19<sup>th</sup>&nbsp;CC to 56.42 in the new CC, which indicates more female members from 20<sup>th</sup>&nbsp;CC may get another opportunity in the 21<sup>st</sup>&nbsp;CC in 2027.</p>
<div class='tableauPlaceholder' id='viz1687129390332' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='Ethnicity1 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_ethnicity&#47;Ethnicity1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='20thCCProject_ethnicity&#47;Ethnicity1' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_ethnicity&#47;Ethnicity1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129390332');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;color:#000;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;">In terms of ethnic composition, there are 17 ethnic groups including Han have been represented in the 20<sup>th</sup>&nbsp;CC. Han has the largest representation comprising of 343 members (91.22%). Other 16 ethnic groups have 33 members altogether which makes up for 8.51% of total membership. This is significantly lower compared to 19<sup>th</sup>&nbsp;CC where there were 42 members (11.32%) from non-Han groups. Thus, it puts question mark on Xi Jinping&rsquo;s claim of &lsquo;promoting ethnic unity and progress&rsquo;, made during his speech at the 20<sup>th</sup>&nbsp;Party Congress.</p>
<div class='tableauPlaceholder' id='viz1687129402841' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='Ethnicty2 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_ethnicity2&#47;Ethnicty2&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='20thCCProject_ethnicity2&#47;Ethnicty2' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_ethnicity2&#47;Ethnicty2&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129402841');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;">Among non-Han ethnic groups, Tibetans and Manchu comprise the largest proportion followed by Mongol, Zhuang, Miao and Hui. Among the full members 195 out of 205 members (95.12%) belong to Han ethnicity whereas 148 alternate members (86.55%) are also Han people. However, continuing the trend, no person from ethnic minorities could earn a seat in the Politburo. &nbsp;&nbsp;&nbsp;</p>
<h3 style="text-align: justify;color:#000;"><strong>Geographic Distribution</strong></h3>
<div class='tableauPlaceholder' id='viz1687129543679' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='Geo Dash ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;DB&#47;DBS3FYW72&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='path' value='shared&#47;DBS3FYW72' /> <param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;DB&#47;DBS3FYW72&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='tabs' value='no' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129543679');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;color:#000;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;">Geographic distribution of birth provinces of the CC members is mostly in line with the population of provinces. China&rsquo;s coastal provinces are densely populated provinces and thus, have more representation in the CC. Jiangsu has the largest representation with 46 members followed by Shandong with 40 members. Other coastal provinces like Shanghai (4), Fujian (22), Zhejiang (27) and Liaoning (23) also have sizeable representation in the CC. Altogether, coastal provinces account for 174 members (46.27%) &ndash; indicating their dominance in Chinese politics Coastal provinces also have economic importance for China as they are wealthier, more externally connected and contribute more to China&rsquo;s GDP. On the other hand, there are some inland provinces like Henan (29), Hunan (23) and Shaanxi (16) that also have substantial representation. Surprisingly, Guangdong, China&rsquo;s richest province has only two members.</p>
<p style="text-align: justify;">&nbsp;</p>
<h3 style="text-align: justify;color:#000;"><strong>Age Distribution</strong></h3>
<div class='tableauPlaceholder' id='viz1687129573154' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='Age Dash ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_age&#47;AgeDash&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='20thCCProject_age&#47;AgeDash' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_age&#47;AgeDash&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129573154');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;">The analysis of age composition of the CC members tells us about their prospects for promotion or retirement. China&rsquo;s informal rule of &lsquo;Seven up Eight down&rsquo; has mostly been followed in terms of retirement of old members, except for few notable exceptions like Zhang Youxia, Wang Yi and Xi Jinping &ndash; who all are part of the Politburo. The 20<sup>th</sup>&nbsp;CC has a majority of leaders from 1960s generations who are also eligible for reappointment in the next CC. Leaders from 1950s generation are only part of full membership (37) as they likely to have reached peak of their careers. &nbsp;On the other hand, leaders belonging to 1970s generation are all alternate members (33) as they have more opportunities to get promoted in higher decision-making bodies of China. The majority of members belong to the 1960s generation, with 167 members from full membership (82%) and 131 members from alternate membership (76.61%).</p>
<h3 style="text-align: justify;color:#000;"><strong>Provincial Party Secretaries</strong></h3>
<div class='tableauPlaceholder' id='viz1687129584195' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='Provinvial Party Sec ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_18Jan_pps&#47;ProvinvialPartySec&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='20thCCProject_18Jan_pps&#47;ProvinvialPartySec' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_18Jan_pps&#47;ProvinvialPartySec&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129584195');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;color:#000;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;">The 20<sup>th</sup>&nbsp;CC includes all provincial party secretaries (31), which is 3 more than the number of provincial party secretaries in the 19<sup>th</sup>&nbsp;CC. All provincial party secretaries are Full CC members and they continue to enjoy strong representation in the CC. Party secretaries of Ningxia, Anhui and Shanxi who were not part of the 19<sup>th</sup>&nbsp;CC in 2020 have made their way into the 20<sup>th</sup>&nbsp;CC.</p>
<h3 style="text-align: justify;color:#000;"><strong>Military Officials</strong></h3>
<div class='tableauPlaceholder' id='viz1687129604374' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='Military Officials Dash ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_18Jan_milit&#47;MilitaryOfficialsDash&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='20thCCProject_18Jan_milit&#47;MilitaryOfficialsDash' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_18Jan_milit&#47;MilitaryOfficialsDash&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129604374');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;color:#000;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;">The above list includes all military officials in the 20<sup>th</sup>&nbsp;CC.</p>
<p style="text-align: justify;">&nbsp;</p>
<h3 style="text-align: justify;color:#000;"><strong>Central Military Commission</strong></h3>
<div class='tableauPlaceholder' id='viz1687129618469' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='cmc dasah ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_18Jan_cmc&#47;cmcdasah&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='20thCCProject_18Jan_cmc&#47;cmcdasah' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_18Jan_cmc&#47;cmcdasah&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129618469');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;">The Central Military Commission of the CPC is the highest decision-making body in China in terms of military. It consists of seven members and headed by the Chairman, followed by two vice-chairmen and other four members. Historically, CMC has been an &lsquo;all-men&rsquo; body which is also continued in the 20th CMC. Xi Jinping has continued as the Chairman for the consecutive third term. Apart from him, two members from the previous CMC &ndash; Zhang Youxia and Miao Hua &ndash; have been retained in the new CMC. Zhang Youxia (72) will continue as the vice-chairman of CMC, breaking the age restrictions. Another vice-chairman He Weidong, has been brought into the CMC despite not being CC member in the last term. All CMC members are full members of the CC and hold key positions in China&rsquo;s military apparatus. Except Liu Zhenli (58), all other members in the CMC belong to the 1950s generation which indicates the importance of seniority and experience for the appointment in CMC.</p>
<h3 style="text-align: justify;color:#000;"><strong>Politburo</strong></h3>
<div class='tableauPlaceholder' id='viz1687129630486' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='Politburo Dash ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_18Jan_pb&#47;PolitburoDash&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='20thCCProject_18Jan_pb&#47;PolitburoDash' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_18Jan_pb&#47;PolitburoDash&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129630486');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;color:#000;">The 20<sup>th</sup>&nbsp;Politburo has 24 members, one less than the 19<sup>th</sup>&nbsp;Politburo. The 20<sup>th</sup>&nbsp;politburo has no female members as Sun Chunlan was retired at the 20<sup>th</sup>&nbsp;Party Congress and not replaced with another female candidate. The 20<sup>th</sup>&nbsp;politburo is the first all-male Politburo since 1997. Of the 11 members eligible for retirement at the 20<sup>th</sup>&nbsp;Party Congress, 10 were retired with the exception of Zhang Youxia. Interestingly, four prominent members: Li Keqiang, Hu Chunhua, Wang Yang and Chen Quanguo were not included in the 20<sup>th</sup>&nbsp;Politburo in spite of being eligible to serve another term. Another feature of the 20<sup>th</sup>&nbsp;Politburo is the inclusion of technocrats from priority trade sectors like Ma Xingrui, Yuan Jiajun, Li Ganjie, and Chen Jining.</p>
<h3 style="text-align: justify;color:#000;"><strong>Politburo Standing Committee</strong></h3>
<div class='tableauPlaceholder' id='viz1687129642206' style='position: relative'><noscript><a href='https:&#47;&#47;orcasia.org&#47;'><img alt='PSC Dash ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_psc&#47;PSCDash&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='20thCCProject_psc&#47;PSCDash' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;20&#47;20thCCProject_psc&#47;PSCDash&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1687129642206');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='1000px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p style="text-align: justify;">&nbsp;</p>
<div class="wp-block-spacer" style="text-align: justify;" aria-hidden="true">&nbsp;</div>
<p style="text-align: justify;color:#000;">For a full overview of the Politburo Standing Committee members, refer to this&nbsp;<a href="https://orcasia.org/2022/11/xis-loyalists-a-breakdown-of-chinas-new-leadership/">article</a>&nbsp;on the 20<sup>th</sup>&nbsp;PSC announced after the 20<sup>th</sup>&nbsp;Party Congress.</p>
</div>
</section>




      </div>
      
    </section>
    

    
    




        
        
        
     
   <!-----timeline exit -->
  </main>
    
    @endsection
    
   

  </body>
</html>