
(function(window,document){"use strict";var env_urls=skGetEnvironmentUrls('flickr-album-single');var app_url=env_urls.app_url;var sk_app_url=env_urls.sk_app_url;var app_backend_url=env_urls.app_backend_url;var app_file_server_url=env_urls.app_file_server_url;var sk_img_url=env_urls.sk_img_url;var sk_api_url=env_urls.sk_api_url;var data_storage=[];var last_key=[];var original_data;var el=document.getElementsByClassName('sk-ww-flickr-album-single')[0];var additional_error_messages=[];if(el==undefined){var el=document.getElementsByClassName('dsm-ww-flickr-photo-album-single')[0];el.className="sk-ww-flickr-album-single";}
el.innerHTML="<div class='first_loading_animation' style='text-align:center; width:100%;'><img src='"+app_url+"images/ripple.svg' class='loading-img' style='width:auto !important;' /></div>";if(window.jQuery===undefined){var script_tag=document.createElement('script');script_tag.setAttribute("type","text/javascript");script_tag.setAttribute("src","https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js");if(script_tag.readyState){script_tag.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){scriptLoadHandler();}};}else{script_tag.onload=scriptLoadHandler;}
(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(script_tag);}else{jQuery=window.jQuery;scriptLoadHandler();}
function scriptLoadHandler(){loadScript(app_url+"libs/js/magnific-popup/jquery.magnific-popup.js",function(){loadScript(app_url+"libs/js/swiper/swiper.min.js",function(){$=jQuery=window.jQuery.noConflict(true);main();});});}function loadBioInformation(sk_flickr_photo_album,data){if(getDsmSetting(sk_flickr_photo_album,'show_album_cover_photo')==0&&getDsmSetting(sk_flickr_photo_album,'show_album_name')==0&&getDsmSetting(sk_flickr_photo_album,'show_album_link')==0&&getDsmSetting(sk_flickr_photo_album,'show_album_description')==0&&getDsmSetting(sk_flickr_photo_album,'show_photos_count')==0&&getDsmSetting(sk_flickr_photo_album,'show_likes_count')==0&&getDsmSetting(sk_flickr_photo_album,'show_comments_count')==0){return"";}
var post_items="<div class='flickr-user-root-container'>";if(getDsmSetting(sk_flickr_photo_album,'show_album_cover_photo')==1){if(data&&data.bio.primary){post_items+="<div class='sk-flickr-profile-pic-container'>";post_items+="<div class='flickr-profile-pic' style='background-image:url(https://live.staticflickr.com/"+data.bio.id+"/"+data.bio.primary+"_"+data.bio.secret+".jpg);'></div>";post_items+="</div>";}}
post_items+="<div class='sk-fb-photo-album-profile-info'>";post_items+="<div>";if(getDsmSetting(sk_flickr_photo_album,'show_album_name')==1){if(data.bio.title){post_items+="<a target='_blank' href='https://www.flickr.com/photos/"+getDsmSetting(sk_flickr_photo_album,'username')+"/albums/"+getDsmSetting(sk_flickr_photo_album,'fb_album_id')+"' class='sk-fb-photo-album-name'>"+data.bio.title+"</a>";}}
post_items+="</div>";post_items+="<div class='sk-fb-photo-album-profile-counts'>";if(getDsmSetting(sk_flickr_photo_album,'show_photos_count')==1&&data.bio.photos>0){post_items+="<span class='sk-fb-photo-album-profile-count-item'><span class='f-w-b'>"+data.bio.photos+"</span> "+getDsmSetting(sk_flickr_photo_album,'photos_text')+"</span>";}
post_items+="</div>";post_items+="<div class='sk-fb-photo-album-description'>";if(getDsmSetting(sk_flickr_photo_album,'show_album_description')==1){post_items+=data.bio.description+" ";}
if(getDsmSetting(sk_flickr_photo_album,'show_album_view_on_flickr_link')==1){post_items+="<div class='sk-flicker-view-on-flicker'>";post_items+="<i class='fa fa-flickr' aria-hidden='true'></i> ";post_items+="<a href='https://www.flickr.com/photos/"+getDsmSetting(sk_flickr_photo_album,'username')+"/albums/"+data.bio.id+"/' target='_blank'> "+getDsmSetting(sk_flickr_photo_album,"view_on_flickr_text")+"</a>";post_items+="</div>";}
post_items+="</div>";post_items+="</div>";post_items+="</div>";return post_items;}
function loadFeed(sk_flickr_photo_album){var embed_id=getDsmEmbedId(sk_flickr_photo_album);var data=original_data;data_storage[embed_id]=data.photos;if(original_data.user_info&&!widgetValidation(sk_flickr_photo_album,original_data)){return;}
else if(!original_data.bio&&(!data.photos||data.photos.length==0)){generateSolutionMessage(sk_flickr_photo_album,embed_id);return;}
else{var post_items="";post_items+=loadBioInformation(sk_flickr_photo_album,data);var enable_button=false;if(data_storage[embed_id].length>0){if(getDsmSetting(sk_flickr_photo_album,'layout')==1||getDsmSetting(sk_flickr_photo_album,'layout')==""){post_items+="<div class='sk-ww-fb-photo-album-popup-gallery sk-fb-photo-album-all-posts'>";last_key[embed_id]=parseInt(getDsmSetting(sk_flickr_photo_album,'post_count'));for(var i=0;i<last_key[embed_id];i++){if(typeof data_storage[embed_id][i]!='undefined'){post_items+=getFeedItem(data_storage[embed_id][i],sk_flickr_photo_album);}}
if(data_storage[embed_id].length>last_key[embed_id]){enable_button=true;}
post_items+="</div>";}
else if(parseInt(getDsmSetting(sk_flickr_photo_album,'layout'))){post_items+=loadSliderLayout(data_storage[embed_id],sk_flickr_photo_album);}}
else{post_items+="<div class='sk-no-photos-found'>";post_items+="<p>No photos found in this Album</p>";post_items+="</div>";}
if(getDsmSetting(sk_flickr_photo_album,'show_load_more_button')==1&&enable_button){post_items+="<div class='sk-fb-photo-album-bottom-btn-container'>";post_items+="<button class='sk-fb-photo-album-load-more-posts'>"+getDsmSetting(sk_flickr_photo_album,'load_more_posts_text')+"</button>";post_items+="</div>";}
if(data.user_info){post_items+=skGetBranding(sk_flickr_photo_album,data.user_info);}
sk_flickr_photo_album.append(post_items);if(getDsmSetting(sk_flickr_photo_album,'layout')==3){skLayoutSliderSetting(sk_flickr_photo_album);skLayoutSliderArrowUI(sk_flickr_photo_album);}
applyCustomUi(jQuery,sk_flickr_photo_album);setTimeout(function(){applyCustomUi(jQuery,sk_flickr_photo_album);},500);replaceContentWithLinks(jQuery('.sk-album-pic-description'),sk_flickr_photo_album);}
if(data.user_info){sk_increaseView(data.user_info);}}
function getFeedItem(val,sk_flickr_photo_album,user_id,bio){var details_link_color=sk_flickr_photo_album.find('.details_link_color').text();var post_items="";var popup_title="";post_items+="<div class='sk-ww-flickr-album-single-item' title=\""+val.title+"\" alt=\""+val.title+"\">";popup_title="";popup_title+="<div class='sk-flicker-view-on-flicker-container'>";popup_title+="<i class='fa fa-flickr' aria-hidden='true'></i> ";popup_title+="<a  style='color: "+details_link_color+" !important' href='https://www.flickr.com/photos/"+original_data.bio.owner+"/"+val.id+"/' target='_blank'> "+getDsmSetting(sk_flickr_photo_album,"view_on_flickr_text")+"</a>";popup_title+="</div>";if(val.title&&val.title.indexOf("\"")!=-1){val.title=val.title.replace(/\"/g,"");}
popup_title+="<div class='sk-album-pic-description'>"+val.title+"&nbsp;</div>";post_items+="<a href='https://live.staticflickr.com/"+val.server+"/"+val.id+"_"+val.secret+"_b.jpg' data-title=\""+popup_title+"\">";post_items+="<div class='sk-fb-photo-album-post-hover display-none'>";post_items+="<span class='m-r-15px'>";post_items+="</span>";post_items+="<span>";post_items+="</span>";post_items+="</div>";post_items+="<div style='background: url(\"https://live.staticflickr.com/"+val.server+"/"+val.id+"_"+val.secret+".jpg\") 0% 0% / cover no-repeat;' class='sk-fb-photo-album-post-img'></div>";post_items+="<div class='sk-flickr-info-container'><span>"+val.title+"</span><br>";post_items+="<small>by "+original_data.bio.username+"</small>"
post_items+="</div>";post_items+="</a>";post_items+="</div>";return post_items;}
function checkImage(url){const img=new Image();img.src=url;if(img.complete){return true;}else{img.onload=()=>{return true;};img.onerror=()=>{return false;};}}
function requestFeedData(sk_flickr_photo_album){var embed_id=getDsmEmbedId(sk_flickr_photo_album);var json_url=app_file_server_url+embed_id+".json?nocache="+(new Date()).getTime();jQuery.getJSON(json_url,function(data){original_data=data;loadFeed(sk_flickr_photo_album);}).fail(function(e){generateSolutionMessage(sk_flickr_photo_album,embed_id);return;});}function loadSliderLayout(data,sk_flickr_feed){var column_count=getDsmSetting(sk_flickr_feed,'column_count');column_count=parseInt(column_count);if(jQuery(document).width()<480){column_count=1;}
else if(jQuery(document).width()<750){column_count=column_count>2?2:column_count;}
var post_items="<div class='sk-ww-fb-photo-album-popup-gallery sk-fb-photo-album-all-posts' style='display: block;position: relative;'>";post_items+="<button type='button' class='swiper-button-next ' style='pointer-events: all;'>";post_items+="<i class='fa fa-angle-right'></i>";post_items+="</button>";post_items+="<button type='button' class='swiper-button-prev' style='pointer-events: all;'>";post_items+="<i class='fa fa-angle-left' aria-hidden='true'></i>";post_items+="</button>";post_items+="<div class='swiper-container swiper-layout-slider'>";post_items+="<div class='swiper-wrapper'>";var data_slider=data;console.log(data_slider);var pages=Math.ceil(data_slider.length/column_count);for(var slide=1;slide<=pages;slide++){post_items+="<div class='swiper-slide' >";post_items+="<div class='sk-flickr-album-container'>";var slide_data=getPaginationResult(sk_flickr_feed,data_slider,slide,column_count);jQuery.each(slide_data,function(key,val){if(typeof val!='undefined')
post_items+=getFeedItem(val,sk_flickr_feed);});post_items+="</div>";post_items+="</div>";}
post_items+="</div>";post_items+="</div>";post_items+="</div>";return post_items;}
function getPaginationResult(sk_flickr_feed,post_data,page,column_count){var start=0;var end=parseInt(column_count);var multiplicand=page-1;var return_post_data=[];if(page!=1){start=multiplicand*end;end=start+end;}
if((end-1)>post_data.length){end=post_data.length;}
for(var i=start;i<end;i++){return_post_data.push(post_data[i]);}
return return_post_data;}
function skLayoutSliderSetting(sk_flickr_feed){var autoplay=false;var loop=false;if(getDsmSetting(sk_flickr_feed,"autoplay")==1){var delay=getDsmSetting(sk_flickr_feed,"delay")*1500;autoplay={delay:delay};loop=true;}
try{var swiper=new Swiper('.swiper-layout-slider.swiper-container',{loop:loop,autoplay:autoplay,navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev',},});}catch(error){console.log(error);}
console.log(swiper);}
function skLayoutSliderArrowUI(sk_flickr_feed){var arrow_background_color=getDsmSetting(sk_flickr_feed,"arrow_background_color");var arrow_color=getDsmSetting(sk_flickr_feed,"arrow_color");var arrow_opacity=getDsmSetting(sk_flickr_feed,"arrow_opacity");console.log(arrow_background_color);console.log(arrow_color);console.log(arrow_opacity);console.log(sk_flickr_feed.find(".swiper-button-prev i,.swiper-button-next i"));sk_flickr_feed.find(".swiper-button-prev i,.swiper-button-next i").mouseover(function(){jQuery(this).css({"opacity":"1","border-color":arrow_background_color,});}).mouseout(function(){jQuery(this).css({"border-color":arrow_color,"opacity":arrow_opacity});});sk_flickr_feed.find(".swiper-button-prev i, .swiper-button-next i").css({"border-color":arrow_color,"opacity":arrow_opacity,"color":arrow_color,});var feed_h=sk_flickr_feed.find('.sk-flickr-feed-item .sk-ig-post-img').innerHeight();var feed_h_2=feed_h/2;sk_flickr_feed.find(".swiper-button-prev,.swiper-button-next").css({"top":feed_h_2+"px"});}
function applyCustomUi(jQuery,sk_flickr_photo_album){sk_flickr_photo_album.find(".loading-img").hide();sk_flickr_photo_album.css({'width':'100%'});var sk_flickr_photo_album_width=sk_flickr_photo_album.width();sk_flickr_photo_album.css({'height':'auto'});var column_count=sk_flickr_photo_album.find('.column_count').text();if(sk_flickr_photo_album_width<=320||sk_flickr_photo_album_width<=481){column_count=1;}
if(sk_flickr_photo_album_width>=482&&sk_flickr_photo_album_width<=780){column_count=2;}
var border_size=0;var background_color="#555555";var space_between_images=sk_flickr_photo_album.find('.space_between_images').text();var margin_between_images=parseFloat(space_between_images).toFixed(2)/2;sk_flickr_photo_album_width=sk_flickr_photo_album.find('.sk-flickr-album-container').width()||sk_flickr_photo_album.find('.sk-fb-photo-album-all-posts').width();var total_space_between_images=parseFloat(space_between_images).toFixed(2)*parseFloat(column_count);var pic_width=(sk_flickr_photo_album_width/column_count)-(margin_between_images*2);var font_family=sk_flickr_photo_album.find('.font_family').text();var title_all_caps=sk_flickr_photo_album.find('.title_all_caps').text();var title_font_color=sk_flickr_photo_album.find('.title_font_color').text();var title_font_size=sk_flickr_photo_album.find('.title_font_size').text();var details_bg_color=sk_flickr_photo_album.find('.details_bg_color').text();var details_font_color=sk_flickr_photo_album.find('.details_font_color').text();var details_link_color=sk_flickr_photo_album.find('.details_link_color').text();var details_link_hover_color=sk_flickr_photo_album.find('.details_link_hover_color').text();var details_all_caps=sk_flickr_photo_album.find('.details_all_caps').text();var button_bg_color=sk_flickr_photo_album.find('.button_bg_color').text();var button_text_color=sk_flickr_photo_album.find('.button_text_color').text();var button_hover_bg_color=sk_flickr_photo_album.find('.button_hover_bg_color').text();var button_hover_text_color=sk_flickr_photo_album.find('.button_hover_text_color').text();if(title_all_caps==1){sk_flickr_photo_album.find('.sk-fb-photo-album-name').css({'text-transform':'uppercase','color':title_font_color,'font-size':title_font_size+'px'});}else{sk_flickr_photo_album.find('.sk-fb-photo-album-name').css({'color':title_font_color,'font-size':title_font_size+'px'});}
if(details_all_caps==1){sk_flickr_photo_album.find('.sk-fb-photo-album-profile-counts, .sk-fb-photo-album-description').css({'text-transform':'uppercase'});}
sk_flickr_photo_album.find('.sk-ww-flickr-album-single-item').css({'width':pic_width+'px','height':pic_width+'px','margin':margin_between_images+'px','background-color':background_color,'padding':border_size});sk_flickr_photo_album.find('.sk-ww-flickr-album-single-item').css({'width':pic_width+'px','height':pic_width+'px','margin':margin_between_images+'px','background-color':background_color,'padding':border_size});sk_flickr_photo_album.find('.sk-ww-flickr-album-single-item').mouseover(function(){$(this).find('.sk-flickr-info-container').css('display','block');});sk_flickr_photo_album.find('.sk-ww-flickr-album-single-item').mouseout(function(){$(this).find('.sk-flickr-info-container').css('display','none');});var hover_width=sk_flickr_photo_album.find('.sk-ww-flickr-album-single-item').width();sk_flickr_photo_album.find('.sk-fb-photo-album-post-hover').css({'width':hover_width+'px','height':hover_width+'px','margin':0,'padding':0,'line-height':hover_width+'px'});sk_flickr_photo_album.find('.sk-ww-flickr-album-single-item .sk-fb-photo-album-post-img').css({'width':pic_width+'px','height':pic_width+'px'});sk_flickr_photo_album.css({'font-family':font_family,'background-color':details_bg_color,'width':'100%'});jQuery('.sk-pop-ig-post').css({'font-family':font_family});sk_flickr_photo_album.find('.flickr-user-root-container').css({'color':details_font_color});sk_flickr_photo_album.find('.flickr-user-root-container a').css({'color':details_link_color});sk_flickr_photo_album.find('.sk-fb-photo-album-profile-info').css({'text-align':'left'});$(".flickr-user-root-container a").mouseover(function(){$(this).css({'color':details_link_hover_color});}).mouseout(function(){$(this).css({'color':details_link_color});});var margin_bottom_sk_ig_load_more_posts=parseFloat(space_between_images)/parseFloat(2);if(margin_bottom_sk_ig_load_more_posts==0){margin_bottom_sk_ig_load_more_posts=3;}
sk_flickr_photo_album.find(".sk-fb-photo-album-load-more-posts").css({'margin-bottom':margin_bottom_sk_ig_load_more_posts+'px'});sk_flickr_photo_album.find(".flickr-user-container, .sk-fb-photo-album-load-more-posts, .sk-fb-photo-album-bottom-follow-btn").css({'background-color':button_bg_color,'border-color':button_bg_color,'color':button_text_color});sk_flickr_photo_album.find(".flickr-user-container, .sk-fb-photo-album-load-more-posts, .sk-fb-photo-album-bottom-follow-btn").mouseover(function(){$(this).css({'background-color':button_hover_bg_color,'border-color':button_hover_bg_color,'color':button_hover_text_color});}).mouseout(function(){$(this).css({'background-color':button_bg_color,'border-color':button_bg_color,'color':button_text_color});});var padding_sk_ig_bottom_btn_container=margin_between_images;if(padding_sk_ig_bottom_btn_container==0){padding_sk_ig_bottom_btn_container=5;}
sk_flickr_photo_album.find(".sk-fb-photo-album-bottom-btn-container").css({'padding':padding_sk_ig_bottom_btn_container+'px'});sk_flickr_photo_album.find('.sk-fb-event-item, .sk_powered_by').css({'margin-bottom':getDsmSetting(sk_flickr_photo_album,"space_between_events")+'px'});applyPopUp(sk_flickr_photo_album,jQuery);jQuery('head').append('<style type="text/css">'+getDsmSetting(sk_flickr_photo_album,"custom_css")+'</style>');}function showPopUp(jQuery,content_src,clicked_element){var show_pop_up_on_middle=jQuery(clicked_element).closest('.sk-ww-flickr-album-single').find('.show_pop_up_on_middle').text();var clicked_element_pos=jQuery(clicked_element).offset().top;var relative_pos=clicked_element_pos-jQuery(window).scrollTop()-200;var flickr_album_single=jQuery(clicked_element).closest('.sk-ww-flickr-album-single');jQuery.magnificPopup.open({items:{src:content_src},'type':'inline',callbacks:{open:function(){if(show_pop_up_on_middle==0){jQuery('.mfp-container').css({'top':relative_pos+'px'});}
if(jQuery('.mfp-content .sk-pop-ig-post video').get(0)!==undefined){jQuery('.mfp-content .sk-pop-ig-post video').get(0).play();}},close:function(){if(show_pop_up_on_middle==0){jQuery('.mfp-container').css({'top':'0px'});}}}});}
function applyPopUp(sk_flickr_photo_album,jQuery){var font_family=sk_flickr_photo_album.find('.font_family').text();if(typeof jQuery.magnificPopup==="undefined")
initManificPopupPlugin(jQuery);jQuery('.sk-ww-fb-photo-album-popup-gallery').magnificPopup({delegate:'a',type:'image',tLoading:"<i class='fa fa-spinner fa-pulse' aria-hidden='true'></i>",mainClass:'mfp-img-mobile',gallery:{enabled:true,navigateByImgClick:true,preload:[0,1]},image:{tError:'<a href="%url%">The image #%curr%</a> could not be loaded.',titleSrc:function(item){return item.el.attr('data-title');}},callbacks:{open:function(){replaceContentWithLinks(jQuery('.mfp-content .sk-album-pic-description'));var popup_padding=20;if(sk_flickr_photo_album.width()>500){popup_padding=getDsmSetting(sk_flickr_photo_album,'popup_padding');}
jQuery('.mfp-content .mfp-title').css({'font-family':font_family,'padding':popup_padding+'px'});jQuery('.mfp-content').css({'margin-bottom':'50px'});if(getDsmSetting(sk_flickr_photo_album,'show_popup_caption')!=1&&getDsmSetting(sk_flickr_photo_album,'show_view_on_flickr')!=1){jQuery('.mfp-container').find('figcaption').hide();}
if(getDsmSetting(sk_flickr_photo_album,'show_popup_caption')!=1){jQuery('.mfp-container').find('.sk-album-pic-description').hide();}
if(getDsmSetting(sk_flickr_photo_album,'show_view_on_flickr')!=1){jQuery('.mfp-container').find('.sk-flicker-view-on-flicker-container').hide();}},close:function(){}}});}
function getDsmEmbedId(sk_flickr_photo_album){var embed_id=sk_flickr_photo_album.attr('embed-id');if(embed_id==undefined){embed_id=sk_flickr_photo_album.attr('data-embed-id');}
return embed_id;}
function getDsmSetting(sk_flickr_photo_album,key){return sk_flickr_photo_album.find("."+key).text();}
function loadScript(url,callback){var scriptTag=document.createElement('script');scriptTag.setAttribute("type","text/javascript");scriptTag.setAttribute("src",url);if(typeof callback!=="undefined"){if(scriptTag.readyState){scriptTag.onreadystatechange=function(){if(this.readyState==='complete'||this.readyState==='loaded'){callback();}};}else{scriptTag.onload=callback;}}
(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(scriptTag);}
function loadCssFile(filename){var fileref=document.createElement("link");fileref.setAttribute("rel","stylesheet");fileref.setAttribute("type","text/css");fileref.setAttribute("href",filename);if(typeof fileref!="undefined"){document.getElementsByTagName("head")[0].appendChild(fileref)}}
function replaceContentWithLinks(html){if(html.hasClass("linked")){return;}
html.addClass("linked");var text=html.html();if(text){text=replaceHttpToLink(text);text=text.replace(/(\r\n|\n\r|\r|\n)/g," <br> ");text=text.replace('#',' #');text=text.replace('@',' @');var splitted_text=text.split(' ');if(splitted_text&&splitted_text.length>0){jQuery.each(splitted_text,function(key,value){if(value.charAt(0)=="#"){var original_text=value.replace('#','');text=text.replace(' '+value,' <a target="_blank" href="https://www.flickr.com/photos/tags/'+original_text+'">'+value+'</a>');}
else if(value.charAt(0)=="@"){var original_text=value.replace('@','');text=text.replace(' '+value,' <a target="_blank" href="https://www.flickr.com/photos/tags/'+original_text+'">'+value+'</a>');}
else if(value.indexOf('www')!=-1&&value.indexOf('href')==-1){var original_text=value.replace('@','');text=text.replace(' '+value,' <a target="_blank" href="https://'+original_text+'">'+original_text+'</a>');}});}
html.html(text);}}
function replaceHttpToLink(content)
{var exp_match=/(\b(https?|):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;var element_content=content.replace(exp_match,'<a class="href_status_trigger hide-link" target="_blank" href="$1">$1</a>');var new_exp_match=/(^|[^\/])(www\.[\S]+(\b|$))/gim;var new_content=element_content.replace(new_exp_match,'$1<a class="href_status_trigger hide-link" target="_blank" href="http://$2">$2</a>');return new_content;}
function loadGoogleFont(font_family){var web_safe_fonts=["Inherit","Impact, Charcoal, sans-serif","'Palatino Linotype', 'Book Antiqua', Palatino, serif","Century Gothic, sans-serif","'Lucida Sans Unicode', 'Lucida Grande', sans-serif","Verdana, Geneva, sans-serif","Copperplate, 'Copperplate Gothic Light', fantasy","'Courier New', Courier, monospace","Georgia, Serif"];if(!web_safe_fonts.includes(font_family)){try{loadCssFile("https://fonts.googleapis.com/css?family="+font_family);}catch(error){}}}
function readableNumber(number){number=parseInt(number);number=number?number.toLocaleString("en-US"):0;return number;}
function addDescriptiveTagAttributes(_sk,add_to_img=true){_sk.find('a').each(function(i,v){var title=jQuery(v).text();jQuery(v).attr('title',title);});if(add_to_img){_sk.find('img').each(function(i,v){var src=jQuery(v).attr('src');jQuery(v).attr('alt','Post image');});}}
function getClientId(){var _gaCookie=document.cookie.match(/(^|[;,]\s?)_ga=([^;,]*)/);if(_gaCookie)return _gaCookie[2].match(/\d+\.\d+$/)[0];}
function getSkEmbedId(sk_class){var embed_id=sk_class.attr('embed-id');if(embed_id==undefined){embed_id=sk_class.attr('data-embed-id');}
return embed_id;}
function getSkSetting(sk_class,key){return sk_class.find("div."+key).text();}
function setCookieSameSite(){document.cookie="AC-C=ac-c;expires=Fri, 31 Dec 2025 23:59:59 GMT;path=/;HttpOnly;SameSite=Lax";}
function getIEVersion(){var sAgent=window.navigator.userAgent;var Idx=sAgent.indexOf("MSIE");if(Idx>0)
return parseInt(sAgent.substring(Idx+5,sAgent.indexOf(".",Idx)));else if(!!navigator.userAgent.match(/Trident\/7\./))
return 11;else
return 0;}
function isSafariBrowser(){var ua=navigator.userAgent.toLowerCase();if(ua.indexOf('safari')!=-1){if(ua.indexOf('chrome')>-1){return 0;}else{return 1;}}}
if(getIEVersion()>0||isSafariBrowser()>0){loadIEScript('https://cdn.jsdelivr.net/bluebird/3.5.0/bluebird.min.js');loadIEScript('https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.3/fetch.js');}
function loadIEScript(url){var scriptTag=document.createElement('script');scriptTag.setAttribute("type","text/javascript");scriptTag.setAttribute("src",url);(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(scriptTag);}
function kFormatter(num){return Math.abs(num)>999?Math.sign(num)*((Math.abs(num)/1000).toFixed(1))+'k':Math.sign(num)*Math.abs(num)}
function sk_increaseView(user_info){try{if(user_info&&user_info.status&&(user_info.status==1||user_info.status==6||user_info.status==7||user_info.status==13)){jQuery.getJSON('https://api.ipify.org?format=json',function(data){var update_views_url="https://views.accentapi.com/add_view.php?user_id="+user_info.id+"&url="+document.URL+"&ip_address="+data.ip+"&embed_id="+user_info.embed_id;if(app_url.includes("local")&&sk_app_url){update_views_url="https://localtesting.com/accentapiviews/add_view.php?user_id="+user_info.id+"&url="+document.URL+"&ip_address="+data.ip+"&embed_id="+user_info.embed_id;}
jQuery.ajax(update_views_url);});}}
catch(err){console.log("Error retrieving ip address.");}}
function isTooDarkColor(hexcolor){var r=parseInt(hexcolor.substr(1,2),16);var g=parseInt(hexcolor.substr(3,2),16);var b=parseInt(hexcolor.substr(4,2),16);if(hexcolor.indexOf('rgb')!=-1){let rgbstr=hexcolor;let v=getRGB(rgbstr);r=v[0];g=v[1];b=v[2];}
b=isNaN(b)?0:b;var yiq=((r*299)+(g*587)+(b*114))/1000;if(yiq<60){}
else{}
return yiq<60?true:false;}
function linkify(html){var temp_text=html.split("https://www.").join("https://");temp_text=temp_text.split("www.").join("https://www.");var exp=/((href|src)=["']|)(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;return temp_text.replace(exp,function(){return arguments[1]?arguments[0]:"<a href=\""+arguments[3]+"\">"+arguments[3]+"</a>"});}
function skGetEnvironmentUrls(folder_name){var scripts=document.getElementsByTagName("script");var scripts_length=scripts.length;var search_result=-1;var other_result=-1;var app_url="https://widgets.sociablekit.com/";var app_backend_url="https://api.accentapi.com/v1/";var app_file_server_url="https://data.accentapi.com/feed/";var sk_app_url="https://sociablekit.com/app/";var sk_api_url="https://api.sociablekit.com/";var sk_img_url="https://images.sociablekit.com/";var sk_fb_sync_url="https://facebook-sync.sociablekit.com/";for(var i=0;i<scripts_length;i++){var src_str=scripts[i].getAttribute('src');if(src_str!=null){var other_folder="";if(folder_name=='facebook-page-playlists'){other_folder='facebook-page-playlist';}
else if(folder_name=='linkedin-page-posts'){other_folder='linkedin-page-post';}
else if(folder_name=='linkedin-profile-posts'){other_folder='linkedin-profile-post';}
else if(folder_name=='facebook-hashtag-posts'){other_folder='facebook-hashtag-feed';}
else if(folder_name=='facebook-page-events'){other_folder='facebook-events';}
else if(folder_name=='facebook-page-posts'){other_folder='facebook-feed';if(document.querySelector(".sk-ww-facebook-feed")){var element=document.getElementsByClassName("sk-ww-facebook-feed")[0];element.classList.add("sk-ww-facebook-page-posts");}}
other_result=src_str.search(other_folder);search_result=src_str.search(folder_name);if(search_result>=1||other_result>=1){var src_arr=src_str.split(folder_name);app_url=src_arr[0];app_url=app_url.replace("displaysocialmedia.com","sociablekit.com");if(app_url.search("local")>=1){app_backend_url="http://localhost:3000/v1/";app_url="https://localtesting.com/SociableKIT_Widgets/";app_file_server_url="https://localtesting.com/SociableKIT_FileServer/feed/";sk_app_url="https://localtesting.com/SociableKIT/";sk_api_url="http://127.0.0.1:8000/";sk_img_url="https://localtesting.com/SociableKIT_Images/";sk_fb_sync_url="https://localtesting.com/SociableKIT_Facebook_Sync/";}
else{app_url="https://widgets.sociablekit.com/";}}}}
return{"app_url":app_url,"app_backend_url":app_backend_url,"app_file_server_url":app_file_server_url,"sk_api_url":sk_api_url,"sk_app_url":sk_app_url,"sk_img_url":sk_img_url,"sk_fb_sync_url":sk_fb_sync_url};}
function changeBackSlashToBR(text){if(text){for(var i=1;i<=10;i++){text=text.replace('\n','</br>');}}
return text;}
function sKGetScrollbarWidth(){var outer=document.createElement('div');outer.style.visibility='hidden';outer.style.overflow='scroll';outer.style.msOverflowStyle='scrollbar';document.body.appendChild(outer);var inner=document.createElement('div');outer.appendChild(inner);var scrollbarWidth=(outer.offsetWidth-inner.offsetWidth);outer.parentNode.removeChild(outer);return scrollbarWidth;}
function isValidURL(url){const urlPattern=/^(http(s)?:\/\/)?(www\.)?[a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$/;return urlPattern.test(url);}
async function showUrlData(element,url,post_id,type="",show_thumbnail=1){element.hide();var check_url=url&&url.includes('&')?encodeURIComponent(url):url;var free_data_url=app_file_server_url.replace("feed/","get_fresh_url_tags.php")+'?post_id='+post_id+'&url='+check_url;var read_one_url=app_file_server_url.replace("feed","url-tags")+post_id+".json";if(jQuery('.sk_version').text()){read_one_url+="?v="+jQuery('.sk_version').text();}
fetch(read_one_url,{method:'get',cache:'no-cache'}).then(async response=>{if(response.ok){let data=await response.json();if(data&&data.status&&data.status==418){displayUrlData(data,element,type,show_thumbnail,post_id);data=await jQuery.ajax(free_data_url);}
return data;}
else{response=await jQuery.ajax(free_data_url);displayUrlData(response,element,type,show_thumbnail,post_id);return response;}}).then(async response=>{if(response!=undefined){displayUrlData(response,element,type,show_thumbnail,post_id);}else{response=await jQuery.ajax(free_data_url);displayUrlData(response,element,type,show_thumbnail,post_id);}}).catch(async error=>{var data=await jQuery.ajax(free_data_url);displayUrlData(data,element,type,show_thumbnail,post_id);});}
async function displayUrlData(response,element,type,show_thumbnail=1,post_id){var meta_holder=jQuery(element);var html="";if(!response||response.error){if(meta_holder.html()){meta_holder.show();}
return;}
if(response.message&&response.message=="Data not available. Please try again."){return;}
if(response.messages&&response.messages.length>0&&response.messages[0]=="PDF files that are over 10Mb are not supported by Google Docs Viewer"){var data=response.url;if(response.url){data=response.url.replace("https://","").split("/");}
if(data.length>0){if(data.length>1){response.title=data[data.length-1];}
response.description=data[0].replace("www.","");}}
if(post_id=="7059257055500492800"){response.url+="?id=122630";}
if(response.html&&meta_holder.closest('.sk-ww-twitter-feed').length>0){html+=response.html;}else if(response.title.includes("NCBI - WWW Error Blocked Diagnostic")){console.log(meta_holder);html+="<a href='"+meta_holder.data('link')+"' link-only target='_blank'>";html+="<div class='sk-link-article-container' style='background: #eeeeee;color: black !important; font-weight: bold !important; border-radius: 2px; border: 1px solid #c3c3c3; box-sizing: border-box; word-wrap: break-word;'>";if(show_thumbnail==1){html+="<image alt='No alternative text description for this image' class='sk-link-article-image sk_post_img_link' onerror='this.style.display=\"none\"' src='"+meta_holder.data('image')+"'/>";}
if(response.title){html+="<div class='sk-link-article-title' style='padding: 8px;'>"+meta_holder.data('title')+"</div>";}
html+="</div>";html+="</a>";}
else{html+="<a href='"+response.url+"' link-only target='_blank'>";html+="<div class='sk-link-article-container' style='background: #eeeeee;color: black !important; font-weight: bold !important; border-radius: 2px; border: 1px solid #c3c3c3; box-sizing: border-box; word-wrap: break-word;'>";if(show_thumbnail==1){html+="<image alt='No alternative text description for this image' class='sk-link-article-image sk_post_img_link' onerror='this.style.display=\"none\"' src='"+response.thumbnail_url+"'/>";}
if(response.title){html+="<div class='sk-link-article-title' style='padding: 8px;'>"+response.title+"</div>";}
else if(response.url&&response.url.indexOf(".pdf")!=-1){html+=response.html;}
if(type&&type==6){if(response.description&&response.description.length>0){response.description=response.description.length>140?response.description.substring(0,140)+' ...':response.description;}}
if(response.description&&response.description.indexOf("[vc_row]")!==-1&&response.url){var pathArray=response.url.split('/');var protocol=pathArray[0];if(pathArray.length>2){var host=pathArray[2];var url=protocol+'//'+host;html+="<div class='sk-link-article-description' style='padding: 8px;color: grey;font-weight: 100;font-size: 14px;'>"+url+"</div>";}}
else if(response.description&&response.description.indexOf("fb_built")==-1&&response.description!="null"){if(response.url){var domain=new URL(response.url).hostname;response.description=domain;}
html+="<div class='sk-link-article-description' style='padding: 8px;color: #000000;font-weight: 100;font-size: 14px;'>"+response.description+"</div>";}
else if(response.url&&response.url.includes('instagram.com/p/')){html+="<image style='padding: 8px;' alt='No alternative text description for this image' class='sk-ig-default' onerror='this.style.display=\"none\"' src='https://i1.wp.com/sociablekit.com/wp-content/uploads/2019/01/instagram.png'/>";html+="<div class='sk-link-article-description' style='padding: 8px;margin-left:15%;color: #000000;font-weight: 600;font-size: 14px;'>View this post in instagram</div>";html+="<div class='sk-link-article-description' style='padding: 0px 8px ;margin-left:15%;margin-bottom:10px;color: #000000;font-weight: 100;font-size: 10px;'>"+response.url+"</div>";}
html+="</div>";html+="</a>";}
meta_holder.html(html);meta_holder.css('display','block');meta_holder.css('margin-bottom','15px');meta_holder.find('.sk-ig-default').closest('.sk-link-article-container').css('display','inline-block');meta_holder.find('.sk-ig-default').closest('.sk-link-article-container').css('width','100%');meta_holder.find('.sk-ig-default').css('width','20%');meta_holder.find('.sk-ig-default').css('float','left');applyMasonry();}
function slugifyString(str){str=str.replace(/^\s+|\s+$/g,'');str=str.toLowerCase();var from="ÁÄÂÀÃÅČÇĆĎÉĚËÈÊẼĔȆÍÌÎÏŇÑÓÖÒÔÕØŘŔŠŤÚŮÜÙÛÝŸŽáäâàãåčçćďéěëèêẽĕȇíìîïňñóöòôõøðřŕšťúůüùûýÿžþÞĐđßÆa·/_,:;";var to="AAAAAACCCDEEEEEEEEIIIINNOOOOOORRSTUUUUUYYZaaaaaacccdeeeeeeeeiiiinnooooooorrstuuuuuyyzbBDdBAa------";for(var i=0,l=from.length;i<l;i++){str=str.replace(new RegExp(from.charAt(i),'g'),to.charAt(i));}
str=str.replace(/[^a-z0-9 -]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-');return str;}
function skGetBranding(sk_,user_info){sk_.find('.sk_branding').remove();sk_.find('div.user_email').remove();var html="";if(!user_info)
return;var slugify_string="";if(user_info.solution_name){slugify_string=slugifyString(user_info.solution_name);user_info.tutorial_link="https://www.sociablekit.com/tutorials/embed-"+slugify_string+"-website/";if(user_info.website_builder){user_info.tutorial_link="https://www.sociablekit.com/tutorials/embed-"+slugify_string;slugify_string=slugifyString(user_info.website_builder);user_info.tutorial_link=user_info.tutorial_link+"-"+slugify_string;}}
if(user_info.type==9){user_info.tutorial_link="https://www.sociablekit.com/sync-facebook-page-events-to-google-calendar/";}
else if(user_info.type==26){user_info.tutorial_link="https://www.sociablekit.com/how-to-sync-facebook-group-events-to-google-calendar-on-website/";}
if(user_info.show_branding&&(user_info.show_branding==1||user_info.show_branding=="true")||user_info.show_branding==true){var fontFamily=getSkSetting(sk_,"font_family");var link_color=getSkSetting(sk_,"details_link_color");var details_bg_color=getSkSetting(sk_,"details_bg_color");if(link_color==""){link_color="rgb(52, 128, 220)";}
if(details_bg_color&&isTooDarkColor(link_color)==false&&isTooDarkColor(details_bg_color)==false){link_color='#3480dc';}
var temporary_tutorial_link=user_info.tutorial_link;if(temporary_tutorial_link.endsWith("/")==false){temporary_tutorial_link=temporary_tutorial_link+"/";}
var linkedin_widgets=[33,34,44,58,75,99,100,103];if(linkedin_widgets.includes(user_info.type)&&user_info.embed_id%2==1){var website_builder="website";if(user_info.website_builder){website_builder=slugifyString(user_info.website_builder);}
temporary_tutorial_link="https://www.sociablekit.com/tutorials/embed-linkedin-feed-"+website_builder+"/";}
if(user_info.type==5&&user_info.embed_id%2==1){temporary_tutorial_link=temporary_tutorial_link.replace("profile","feed")}
var facebook_feed=[1,4,9,10,11,36,38,43,12,24,26,49,2,8,3,18,19,28,30,61];if(facebook_feed.includes(user_info.type)&&user_info.embed_id%2==1){var website_builder="website";if(user_info.website_builder){website_builder=slugifyString(user_info.website_builder);}
temporary_tutorial_link="https://www.sociablekit.com/tutorials/embed-facebook-feed-"+website_builder+"/";}
var threads_feed=[110];if(threads_feed.includes(user_info.type)&&user_info.embed_id%2==0){var website_builder="website";if(user_info.website_builder){website_builder=slugifyString(user_info.website_builder);}
temporary_tutorial_link="https://www.sociablekit.com/tutorials/embed-threads-"+website_builder+"/";}
var nofollow_attribute="";if(window.location.href.includes("clean-concept-plus")){nofollow_attribute="rel='nofollow'";}
html+="<div class='sk_branding' style='padding:10px; display:block !important; text-align:center; text-decoration: none !important; color:#555; font-family:"+fontFamily+"; font-size:15px;'>";html+="<a "+nofollow_attribute+" class='tutorial_link' href='"+temporary_tutorial_link+"' target='_blank' style='text-underline-position:under; color:"+link_color+";font-size:15px;'>";if(linkedin_widgets.includes(user_info.type)&&user_info.embed_id%2==1){html+="Embed LinkedIn Feed on your ";if(user_info.website_builder&&user_info.website_builder!="Website"){html+=user_info.website_builder;}}else if(facebook_feed.includes(user_info.type)&&user_info.embed_id%2==1){html+="Embed Facebook Feed on your ";if(user_info.website_builder&&user_info.website_builder!="Website"){html+=user_info.website_builder;}}else{html+="Embed "+user_info.solution_name+" on your ";if(user_info.website_builder&&user_info.website_builder!="Website"){html+=user_info.website_builder;}}
html+=" website";html+="</a>";html+="</div>";}
return html;}
function getRGB(rgbstr){return rgbstr.substring(4,rgbstr.length-1).replace(/ /g,'').replace('(','').split(',');}
function freeTrialEndedMessage(solution_info){var sk_error_message="<div class='sk_trial_ended_message'>";sk_error_message+="Customized feed is powered by <strong><a href='https://www.sociablekit.com/' target='_blank'>SociableKIT</a></strong>.<br>";sk_error_message+="If you're the owner of this website, your 7-day Free Trial has ended.<br>";sk_error_message+="If you want to continue using our services, please <strong><a target='_blank' href='https://www.sociablekit.com/app/users/subscription/subscription'>subscribe now</a></strong>.";sk_error_message+="</div>";return sk_error_message;}
function privateFBGroupMessage(){var sk_error_message="<div class='sk_trial_ended_message'>";sk_error_message+="<h2>The Facebook group is private, it must be <a target='_blank' href='https://www.facebook.com/community/using-key-groups-tools/understanding-your-privacy-settings/'>public</a>.</h2>";sk_error_message+="</div>";return sk_error_message;}
function isFreeTrialEnded(start_date){var start_date=new Date(start_date);var current_date=new Date();var difference=current_date.getTime()-start_date.getTime();difference=parseInt(difference/(1000*60*60*24));return difference>7?true:false;}
function unableToLoadSKErrorMessage(solution_info,additional_error_messages){var sk_error_message="<ul class='sk_error_message'>";sk_error_message+="<li><a href='"+solution_info.embed_id+"' target='_blank'>Customized "+solution_info.solution_name+" feed by SociableKIT</a></li>";console.log(solution_info);sk_error_message+="<li>Unable to load "+solution_info.solution_name+".</li>";for(var i=0;i<additional_error_messages.length;i++){sk_error_message+=additional_error_messages[i];}
sk_error_message+="<li>If you think there is a problem, <a target='_blank' href='https://go.crisp.chat/chat/embed/?website_id=2e3a484e-b418-4643-8dd2-2355d8eddc6b'>chat with support here</a>. We will solve it for you.</li>";sk_error_message+="</ul>";return sk_error_message;}
function widgetValidation(_sk,data){if(data.user_info){var user_info=data.user_info;user_info.trial_ended=false;if(user_info.status==7&&user_info.cancellation_date){var cancellation_date=new Date(user_info.cancellation_date).setHours(0,0,0,0);var current_date=new Date().setHours(0,0,0,0);user_info.show_feed=current_date>cancellation_date?false:true;var activation_date=new Date(user_info.activation_date).setHours(0,0,0,0);if(activation_date>cancellation_date){user_info.show_feed=true;}}
else if(user_info.status==0||user_info.status==2||user_info.status==10){user_info.show_feed=false;}
if(user_info.type==43||user_info.type==38||user_info.type==50){var sk_error_message="<div class='sk_error_message'>";sk_error_message+="<p style='text-align: center !important; margin: 1rem'>"+user_info.solution_name+" are currently unavailable, please choose another <a href='https://www.sociablekit.com/demos/' target='_blank'>widget here</a></p>";sk_error_message+="</div>";_sk.find(".first_loading_animation").hide();_sk.html(sk_error_message);return;}
else if(!user_info.show_feed){var sk_error_message=generateBlueMessage(_sk,user_info);_sk.find(".first_loading_animation").hide();_sk.html(sk_error_message);return;}
else if(user_info.widget_status==1){var sk_error_message=generateBlueMessage(_sk,user_info);_sk.find(".first_loading_animation").hide();_sk.html(sk_error_message);return;}
return user_info.show_feed;}}
function generateBlueMessage(_sk,user_info){var tutorial_link="";var sk_error_message="";if(user_info.solution_name){var slugify_string=slugifyString(user_info.solution_name);tutorial_link="https://www.sociablekit.com/tutorials/embed-"+slugify_string+"-website/";}
if(user_info.type==9){tutorial_link="https://www.sociablekit.com/sync-facebook-page-events-to-google-calendar/";}
else if(user_info.type==26){tutorial_link="https://www.sociablekit.com/how-to-sync-facebook-group-events-to-google-calendar-on-website/";}
if(user_info.widget_status==1){var sk_error_message="<div class='sk_error_message'>";sk_error_message+="<p style='text-align: center !important; margin: 1rem'> The widget does not exist. If you think this is a mistake, please contact support</a></p>";sk_error_message+="</div>";return sk_error_message;}
if(user_info.show_feed==false){if(!user_info.message||user_info.message==""){var sk_error_message="<ul class='sk_error_message'>";sk_error_message+="<li><a href='"+tutorial_link+"' target='_blank'>"+user_info.solution_name+" powered by SociableKIT</a></li>";sk_error_message+="<li>If you’re the owner of this website or SociableKIT account used, we found some errors with your account.</li>";sk_error_message+="<li>Please login your SociableKIT account to fix it.</li>";sk_error_message+="</ul>";user_info.message=sk_error_message;}
sk_error_message=user_info.message;}
else if(user_info.solution_name==null&&user_info.type==null&&user_info.start_date==null){sk_error_message="<p class='sk_error_message'>";sk_error_message+="The SociableKIT solution does not exist. If you think this is a mistake, please contact support.";sk_error_message+="</p>";}
else{sk_error_message="<div class='sk_error_message'>";sk_error_message+="<div style='display: inline-flex;width:100%;'>";sk_error_message+="<div>";sk_error_message+="<h4>SociableKIT is currently syncing your <a href='"+tutorial_link+"' target='_blank'>"+user_info.solution_name+" widget.</a></h4>";sk_error_message+=`<svg width="480"height="20"><rect x="0"y="0"width="480"height="20"fill="#f0f0f0"rx="10"ry="10"/><pattern id="stripes"x="0"y="0"width="20"height="20"patternUnits="userSpaceOnUse"patternTransform="rotate(45)"><rect x="0"y="0"width="10"height="20"fill="#007bff"/></pattern><rect id="progressBar"x="0"y="0"width="0"height="20"fill="url(#stripes)"rx="10"ry="10"><animate attributeName="width"attributeType="XML"from="0"to="480"dur="2s"repeatCount="indefinite"/></rect></svg>`;sk_error_message+="<p>While waiting there are a few things you need to know:</p>";sk_error_message+="<ul>";sk_error_message+="<li>It usually takes only a few minutes. We appreciate your patience.</li>";sk_error_message+="<li>We will notify you via email once your "+user_info.solution_name+" feed is ready.</li>";if(user_info.type==5){sk_error_message+="<li>Make sure your instagram account <a target='_blank' href='https://www.instagram.com/"+getDsmSetting(_sk,'username')+"' target='_blank'><b>@"+getDsmSetting(_sk,'username')+"</b></a> is connected.</li>";}
else if(user_info.type==22||user_info.type==39){sk_error_message+="<li>Please make sure that you selected the correct Google Place or that the <a href='https://www.sociablekit.com/how-to-identify-google-place-id/' target='blank'><b> Google Place ID </b></a> you entered is correct.</li>";}
else{sk_error_message+="<li>Please make sure that the <b> Source ID/Username </b> you enter is correct.</li>";}
sk_error_message+="<li>If you think there is a problem, <a target='_blank' href='https://go.crisp.chat/chat/embed/?website_id=2e3a484e-b418-4643-8dd2-2355d8eddc6b'>chat with support here</a>. We will solve it for you.</li>";sk_error_message+="</ul>";sk_error_message+="</div>";sk_error_message+="</div>";sk_error_message+="</div>";}
return sk_error_message;}
function generateSolutionMessage(_sk,embed_id){var json_url=sk_api_url+"api/user_embed/info/"+embed_id;var sk_error_message="";jQuery.getJSON(json_url,function(data){if(data.type==1&&data.encoded==true){loadEvents(_sk);}
else if(data.type==44&&data.encoded==true){loadFeed(_sk);}
else if(data.type==58&&data.encoded==true){var no_data_text=_sk.find('.no_data_text').text();_sk.html("<div style='padding: 20px;text-align: center;'>"+no_data_text+"</div>");}
else if(data.type==67&&data.encoded==true){loadEvents(_sk);}
else if(data.type==74&&data.encoded==true){_sk.html("<div>No jobs yet, please try again later.</div>");}
else if((data.type==12||data.type==26||data.type==24||data.type==49)&&data.encoded==true){_sk.html(privateFBGroupMessage());}
else{var sk_error_message=generateBlueMessage(_sk,data);_sk.find(".first_loading_animation").hide();_sk.html(sk_error_message);}}).fail(function(e){console.log(e);});}
function copyInput(copy_button,copy_input){var copy_button_orig_html=copy_button.html();copy_input.select();try{var successful=document.execCommand('copy');var msg=successful?'successful':'unsuccessful';if(msg=='successful'){copy_button.html("<i class='fa fa-clipboard'></i> Copied!");setTimeout(function(){copy_button.html(copy_button_orig_html);},3000);}
else{alert('Copying text command was '+msg+'.');}}
catch(err){alert('Oops, unable to copy.');}}
function getDefaultLinkedInPageProfilePicture(profile_picture){if(profile_picture&&profile_picture.indexOf("data:image/gif")!=-1){profile_picture="https://gmalcilk.sirv.com/iamge.JPG";}
return profile_picture;}
function detectedSKDashboard(){let parent_url=(window.location!=window.parent.location)?document.referrer:document.location.href;if(parent_url&&(parent_url.indexOf("sociablekit.com")!=-1||parent_url.indexOf("local")!=-1)){return true;}
return false;}
function getSKDashboardPremiumTrialMessage(){var sk_error_message="";sk_error_message+="<ul class='sk_error_message'>";sk_error_message+="<li>Your 7-days premium trial has ended.</li>";sk_error_message+="<li>Please purchase a <a href='https://www.sociablekit.com/app/users/subscription/subscription?action=subscribe_now'>SociableKIT subscription plan</a> ";sk_error_message+="to save your widget customizations, save time with automatic sync, enjoy priority support, and get a 50% discount on any annual plans. Don’t miss out!</li>";sk_error_message+="<li>You may also choose to <a href='https://help.sociablekit.com/en-us/article/how-to-activate-the-free-plan-1l3o0nt/'>activate the free plan</a> if you don't need our premium features.</li>";sk_error_message+="</ul>";return sk_error_message;}
function getSocialIcon(category)
{var post_items='';if(category.indexOf("Facebook")!=-1){post_items+="<i class='fab fa-facebook' aria-hidden='true'></i>";}
else if(category.indexOf("Instagram")!=-1){post_items+="<i class='fab fa-instagram' aria-hidden='true'></i>";}
else if(category.indexOf("Linkedin")!=-1){post_items+="<i class='fab fa-linkedin' aria-hidden='true'></i>";}
else if(category.indexOf("Youtube")!=-1){post_items+="<i class='fab fa-youtube' aria-hidden='true'></i>";}
else if(category.indexOf("Google")!=-1){post_items+="<i class='fab fa-google' aria-hidden='true'></i>";}
else if(category.indexOf("Twitter")!=-1){post_items+='<i class="fa-brands fa-x-twitter"></i>';}
else if(category.indexOf("Twitch")!=-1){post_items+="<i class='fab fa-twitch' aria-hidden='true'></i>";}
else if(category.indexOf("Yelp")!=-1){post_items+="<i class='fab fa-yelp' aria-hidden='true'></i>";}
else if(category.indexOf("Vimeo")!=-1){post_items+="<i class='fab fa-vimeo' aria-hidden='true'></i>";}
else if(category.indexOf("Twitch")!=-1){post_items+="<i class='fab fa-twitch' aria-hidden='true'></i>";}
else if(category.indexOf("Trust")!=-1){post_items+="<i class='fab fa-trustpilot' aria-hidden='true'></i>";}
else if(category.indexOf("Spot")!=-1){post_items+="<i class='fab fa-spotify' aria-hidden='true'></i>";}
return post_items;}
function isFontAwesomeLoaded(){var span=document.createElement('span');span.className='fa';span.style.display='none';document.body.insertBefore(span,document.body.firstChild);var font=css(span,'font-family');if(font.indexOf("fontawesome")==-1){return false;}
document.body.removeChild(span);return true;}
function css(element,property){let font=window.getComputedStyle(element,null).getPropertyValue(property);if(font){font=font.toLowerCase();return font.replace(/' '/g,"");}
return'na';}
function main(){function loadSettingsData(sk_flickr_photo_album,json_settings_url,json_feed_url){fetch(json_feed_url,{method:'get'}).then(function(response){if(!response.ok){loadSettingsData(sk_flickr_photo_album,json_settings_url,json_settings_url)
return;}
response.json().then(function(data){var settings_data=data;original_data=data;if(data.settings){settings_data=data.settings;settings_data.type=59;}
if(!settings_data.type){loadSettingsData(sk_flickr_photo_album,json_settings_url,json_settings_url)
return;}
settings_data.type=59;var web_safe_fonts=["Inherit","Impact, Charcoal, sans-serif","'Palatino Linotype', 'Book Antiqua', Palatino, serif","Century Gothic, sans-serif","'Lucida Sans Unicode', 'Lucida Grande', sans-serif","Verdana, Geneva, sans-serif","Copperplate, 'Copperplate Gothic Light', fantasy","'Courier New', Courier, monospace","Georgia, Serif"];var is_font_included=web_safe_fonts.indexOf(settings_data.font_family);if(is_font_included<0){loadCssFile("https://fonts.googleapis.com/css?family="+settings_data.font_family);}
loadCssFile("https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css");if(settings_data.show_feed==false){sk_flickr_photo_album.prepend(settings_data.message);sk_flickr_photo_album.find('.loading-img').hide();sk_flickr_photo_album.find('.first_loading_animation').hide();}
else{var settings_html="";settings_data.show_popup_caption=settings_data.show_popup_caption?settings_data.show_popup_caption:1;settings_data.show_view_on_flickr=settings_data.show_view_on_flickr?settings_data.show_view_on_flickr:1;settings_html+="<div style='display:none;' class='display-none sk-settings'>";jQuery.each(settings_data,function(key,value){settings_html+="<div class='"+key+"'>"+value+"</div>";});settings_html+="</div>";if(sk_flickr_photo_album.find('.sk-settings').length){}
else{sk_flickr_photo_album.prepend(settings_html);}
if(getDsmSetting(sk_flickr_photo_album,'layout')==3){loadCssFile(app_url+"libs/swiper/swiper.min.css");loadCssFile(app_url+"libs/swiper/swiper.css?v=ranndomchars");}
if(data.css){jQuery('head').append('<style type="text/css">'+data.css+'</style>');}
else{var sk_version=settings_data.sk_version?settings_data.sk_version:1.0;loadCssFile(app_url+"flickr-album-single/widget_css.php?v="+sk_version);}
loadCssFile(app_url+"libs/js/magnific-popup/magnific-popup.css?v=1.25.25");loadCssFile("https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css");settings_html="";if(data.settings){loadFeed(sk_flickr_photo_album);}
else{requestFeedData(sk_flickr_photo_album);}}});}).catch(function(err){loadSettingsData(sk_flickr_photo_album,json_settings_url,json_settings_url);});}
jQuery(document).ready(function($){jQuery('.sk-ww-flickr-album-single').each(function(){var sk_flickr_photo_album=jQuery(this);var embed_id=getDsmEmbedId(sk_flickr_photo_album);var new_sk_flickr_photo_album_width=jQuery(window).height()+100;sk_flickr_photo_album.height(new_sk_flickr_photo_album_width);var json_settings_url=app_file_server_url.replace('feed','')+"settings/"+embed_id+"/settings.json?nocache="+(new Date()).getTime();var json_feed_url=app_file_server_url+embed_id+".json?nocache="+(new Date()).getTime();loadSettingsData(sk_flickr_photo_album,json_settings_url,json_feed_url);});jQuery(window).resize(function(){jQuery('.sk-ww-flickr-album-single').each(function(){var sk_flickr_photo_album=jQuery(this);applyCustomUi(jQuery,sk_flickr_photo_album);});});jQuery(document).on('click','.sk-ww-flickr-album-single .sk-fb-photo-album-load-more-posts',function(){if(jQuery(this).attr('disabled')=="disabled"){return false;}
jQuery(this).attr('disabled','disabled');var current_btn=jQuery(this);var current_btn_text=current_btn.text();var sk_flickr_photo_album=jQuery(this).closest('.sk-ww-flickr-album-single')
var embed_id=getDsmEmbedId(sk_flickr_photo_album);jQuery(this).html("<i class='fa fa-spinner fa-pulse' aria-hidden='true'></i>");setTimeout(function(){var post_items="";var enable_button=false;var old_last_key=last_key[embed_id];last_key[embed_id]=old_last_key+parseInt(getDsmSetting(sk_flickr_photo_album,'post_count'));for(var i=old_last_key;i<last_key[embed_id];i++){if(typeof data_storage[embed_id][i]!='undefined'){post_items+=getFeedItem(data_storage[embed_id][i],sk_flickr_photo_album);}}
if(data_storage[embed_id].length>last_key[embed_id]){enable_button=true;}
sk_flickr_photo_album.find('.sk-fb-photo-album-all-posts').append(post_items);current_btn.html(current_btn_text);if(enable_button){sk_flickr_photo_album.find('.sk-fb-photo-album-load-more-posts').show();}else{sk_flickr_photo_album.find('.sk-fb-photo-album-load-more-posts').hide();}
current_btn.removeAttr('disabled');applyCustomUi(jQuery,sk_flickr_photo_album);},500);});jQuery(document).on('click','.mfp-arrow',function(){replaceContentWithLinks(jQuery('.mfp-content .sk-album-pic-description'));});});}}(window,document));